apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: efk
  namespace: logging
spec:
  version: 8.6.2
  nodeSets:
  - name: default
    count: 1    
    config:
      node.store.allow_mmap: false 
    volumeClaimTemplates: 
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: nfs-client
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  podTemplate:
    # Limiting Resources consumption
    spec:
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi

