apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.6.2
  count: 1
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 500M
            cpu: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: "/kibana/login"
            port: 5601
  elasticsearchRef:
    name: "efk"
    namespace: logging
  config:
    server:
      basePath: "/kibana"
      rewriteBasePath: true
      publicBaseUrl: "http://ion-cluster.home/kibana"
  http:  # NOTE disabling kibana automatic TLS configuration
    tls:
      selfSignedCertificate:
        disabled: true

