replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: latest
  pullPolicy: IfNotPresent

namespace: mqtt

name: mosquitto

configMap:
  anonymous: true
  listenerPort: 1883
  
persistence:
  enabled: true
  storageClass: nfs-client
  size: 1Gi

passwordFile:
  enabled: false
  username: mqttuser
  password: password
  mountPath: /mosquitto/config
  filename: password.txt

service:
  type: LoadBalancer
  port: 1883
  targetPort: 1883
