apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ include "mosquitto.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.port }}
      targetPort: 1883
  selector:
    app: {{ include "mosquitto.name" . }}