apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config
            - name: mosquitto-passwd
              mountPath: /mosquitto/config/password.txt
          {{- if .Values.passwordFile.enabled }}
            env:
              - name: MQTT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.passwordFile.name }}
                    key: username
              - name: MQTT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.passwordFile.name }}
                    key: password
          {{- end }}
      volumes:
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data
        - name: mosquitto-config
          configMap:
            name: {{ .Values.name }}-cm
        - name: mosquitto-passwd
          configMap:
            name: {{ .Values.name }}
