apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  mosquitto.conf: |-
    allow_anonymous false
    password_file /mosquitto/config/password_file
    listener {{ .Values.configMap.listenerPort }}
    log_dest stderr