apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dash
  namespace: kube-system 
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`192.168.1.153.traefik.me`) && PathPrefix(`/dash`)
    kind: Rule
    services:
    - name: traefik-dashboard
      port: 9000
